# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SaurzCode
email: mail2saurzcode@gmail.com
description: >-
  Big Data, Spark , ML and Data Engineering.
baseurl: "/"
url: "https://saurzcode.in"
read_time: true
words_per_minute: # 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"


category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Build settings
#theme: minimal-mistakes-jekyll
#remote_theme: wowthemesnet/mediumish-theme-jekyll
#theme: just-the-docs
#theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

google_analytics: G-XBR6KYY2X7

disqus:
  shortname: saurzcode

  
#- jekyll-lunr-js-search # for search        


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
markdown: kramdown
highlighter: rouge
input: GFM


# Exclude search.md from search
#lunr_search_exclude: [search.md]

exclude:
  - Gemfile.lock

# Social usernames for developer blog
# Used in layouts for social follow buttons

twitter_username: saurzcode
github_username: saurzcode


copyright: "This site is made with <3 by *me, myself, and I*."


footer_links:
  - title: X
    url: https://x.com/saurzcode
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/saurzcode
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square